<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractReferralsApi Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractReferralsApi
{
    /**
     * GET getAllReferrals
     * Summary: Retrieve rall referrals for a given member.
     * Notes: Returns a list of referrals.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getAllReferrals(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $message = "How about implementing getAllReferrals as a GET method in Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getSingleReferral
     * Summary: Retrieve a single referral by id for a given member.
     * Notes: Returns the requested referral.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSingleReferral(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $id = (key_exists('id', $queryParams)) ? $queryParams['id'] : null;
        $message = "How about implementing getSingleReferral as a GET method in Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postSelfReferral
     * Summary: Supports self-referral.
     * Notes: Creates a new referral of type &#39;Self Referred&#39; in the member&#39;s PDS.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postSelfReferral(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing postSelfReferral as a POST method in Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateReferralStatus
     * Summary: Supports updating the status of a referral.
     * Notes: Updates the status of a member&#39;s referral specified by id. For example, having been referred to a service, the status is set by default to &#39;Referred&#39; and this route enables it to be updated to &#39;Accepted&#39; or &#39;Rejected&#39;
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateReferralStatus(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing updateReferralStatus as a PUT method in Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
