<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractSecureMessagesApi Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractSecureMessagesApi
{
    /**
     * GET getSecureMessageConversation
     * Summary: Retrieve all secure messages for a given conversation.
     * Notes: Returns a list of secure messages that form part of a conversation.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSecureMessageConversation(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $conversationId = (key_exists('conversation_id', $queryParams)) ? $queryParams['conversation_id'] : null;
        $message = "How about implementing getSecureMessageConversation as a GET method in Mydex\ApiPdxSdk\Slim4\Api\SecureMessagesApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postSecureMessageReceive
     * Summary: Supports sending a message to the member&#39;s PDS.
     * Notes: Creates a new received message in the member&#39;s PDS.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postSecureMessageReceive(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing postSecureMessageReceive as a POST method in Mydex\ApiPdxSdk\Slim4\Api\SecureMessagesApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postSecureMessageSend
     * Summary: Supports sending a message from the member&#39;s PDS.
     * Notes: Creates a new sent message in the member&#39;s PDS.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postSecureMessageSend(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing postSecureMessageSend as a POST method in Mydex\ApiPdxSdk\Slim4\Api\SecureMessagesApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
