<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractTimelineApi Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractTimelineApi
{
    /**
     * GET getTimeline
     * Summary: Retrieve list of timeline items.
     * Notes: Returns a list of timeline items which includes: referrals, calendar events and secure messages.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTimeline(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $message = "How about implementing getTimeline as a GET method in Mydex\ApiPdxSdk\Slim4\Api\TimelineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getTimelineItem
     * Summary: Retrieve a single timeline item.
     * Notes: Returns a single timeline item based on feature block and feature block id requested e.g. a &#39;referral&#39; with id 123.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTimelineItem(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $featureBlock = (key_exists('feature_block', $queryParams)) ? $queryParams['feature_block'] : null;
        $featureBlockId = (key_exists('feature_block_id', $queryParams)) ? $queryParams['feature_block_id'] : null;
        $message = "How about implementing getTimelineItem as a GET method in Mydex\ApiPdxSdk\Slim4\Api\TimelineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
