<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractCalendarApi Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractCalendarApi
{
    /**
     * DELETE deleteCalendarEvent
     * Summary: Supports deleting a calendar-event.
     * Notes: Deletes an event in the user&#39;s calendar.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteCalendarEvent(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing deleteCalendarEvent as a DELETE method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getCalendarAppointments
     * Summary: Retrieve appointments for a given context
     * Notes: Returns a list of appointments filtered by context and context_id.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getCalendarAppointments(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $context = (key_exists('context', $queryParams)) ? $queryParams['context'] : null;
        $contextId = (key_exists('context_id', $queryParams)) ? $queryParams['context_id'] : null;
        $message = "How about implementing getCalendarAppointments as a GET method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getCalendarEvents
     * Summary: Retrieve calendar events
     * Notes: Returns a list of calendar events.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getCalendarEvents(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $message = "How about implementing getCalendarEvents as a GET method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postCalendarAppointment
     * Summary: Supports adding a calendar-appointment.
     * Notes: Creates a new appointment in the user&#39;s calendar. An appointment must be made within a specified context e.g. a &#39;Referral&#39;
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postCalendarAppointment(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing postCalendarAppointment as a POST method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST postCalendarEvent
     * Summary: Supports adding a calendar-event.
     * Notes: Creates a new event in the user&#39;s calendar.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function postCalendarEvent(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing postCalendarEvent as a POST method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT putCalendarEvent
     * Summary: Supports updating a calendar-event.
     * Notes: Updates an event in the user&#39;s calendar. For example, updating the &#39;status&#39; from &#39;INVITED&#39; to &#39;CONFIRMED&#39; when a user accepts the invitation to an appointment.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function putCalendarEvent(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $headers = $request->getHeaders();
        $connectionToken = $request->hasHeader('Connection-Token') ? $headers['Connection-Token'] : null;
        $queryParams = $request->getQueryParams();
        $uid = (key_exists('uid', $queryParams)) ? $queryParams['uid'] : null;
        $conId = (key_exists('con_id', $queryParams)) ? $queryParams['con_id'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing putCalendarEvent as a PUT method in Mydex\ApiPdxSdk\Slim4\Api\CalendarApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
