<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Api\CalendarApi;

/**
 * CalendarApiTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Api\CalendarApi
 */
class CalendarApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteCalendarEvent
     *
     * Supports deleting a calendar-event..
     *
     * @covers ::deleteCalendarEvent
     */
    public function testDeleteCalendarEvent()
    {
        self::markTestIncomplete(
            'Test of "deleteCalendarEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getCalendarAppointments
     *
     * Retrieve appointments for a given context.
     *
     * @covers ::getCalendarAppointments
     */
    public function testGetCalendarAppointments()
    {
        self::markTestIncomplete(
            'Test of "getCalendarAppointments" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getCalendarEvents
     *
     * Retrieve calendar events.
     *
     * @covers ::getCalendarEvents
     */
    public function testGetCalendarEvents()
    {
        self::markTestIncomplete(
            'Test of "getCalendarEvents" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postCalendarAppointment
     *
     * Supports adding a calendar-appointment..
     *
     * @covers ::postCalendarAppointment
     */
    public function testPostCalendarAppointment()
    {
        self::markTestIncomplete(
            'Test of "postCalendarAppointment" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postCalendarEvent
     *
     * Supports adding a calendar-event..
     *
     * @covers ::postCalendarEvent
     */
    public function testPostCalendarEvent()
    {
        self::markTestIncomplete(
            'Test of "postCalendarEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for putCalendarEvent
     *
     * Supports updating a calendar-event..
     *
     * @covers ::putCalendarEvent
     */
    public function testPutCalendarEvent()
    {
        self::markTestIncomplete(
            'Test of "putCalendarEvent" method has not been implemented yet.'
        );
    }
}
