<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi;

/**
 * ReferralsApiTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Api\ReferralsApi
 */
class ReferralsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllReferrals
     *
     * Retrieve rall referrals for a given member..
     *
     * @covers ::getAllReferrals
     */
    public function testGetAllReferrals()
    {
        self::markTestIncomplete(
            'Test of "getAllReferrals" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getSingleReferral
     *
     * Retrieve a single referral by id for a given member..
     *
     * @covers ::getSingleReferral
     */
    public function testGetSingleReferral()
    {
        self::markTestIncomplete(
            'Test of "getSingleReferral" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postSelfReferral
     *
     * Supports self-referral..
     *
     * @covers ::postSelfReferral
     */
    public function testPostSelfReferral()
    {
        self::markTestIncomplete(
            'Test of "postSelfReferral" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateReferralStatus
     *
     * Supports updating the status of a referral..
     *
     * @covers ::updateReferralStatus
     */
    public function testUpdateReferralStatus()
    {
        self::markTestIncomplete(
            'Test of "updateReferralStatus" method has not been implemented yet.'
        );
    }
}
