<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Api\SecureMessagesApi;

/**
 * SecureMessagesApiTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Api\SecureMessagesApi
 */
class SecureMessagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSecureMessageConversation
     *
     * Retrieve all secure messages for a given conversation..
     *
     * @covers ::getSecureMessageConversation
     */
    public function testGetSecureMessageConversation()
    {
        self::markTestIncomplete(
            'Test of "getSecureMessageConversation" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postSecureMessageReceive
     *
     * Supports sending a message to the member's PDS..
     *
     * @covers ::postSecureMessageReceive
     */
    public function testPostSecureMessageReceive()
    {
        self::markTestIncomplete(
            'Test of "postSecureMessageReceive" method has not been implemented yet.'
        );
    }

    /**
     * Test case for postSecureMessageSend
     *
     * Supports sending a message from the member's PDS..
     *
     * @covers ::postSecureMessageSend
     */
    public function testPostSecureMessageSend()
    {
        self::markTestIncomplete(
            'Test of "postSecureMessageSend" method has not been implemented yet.'
        );
    }
}
