<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace Mydex\ApiPdxSdk\Slim4\Api;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Api\TimelineApi;

/**
 * TimelineApiTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Api\TimelineApi
 */
class TimelineApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getTimeline
     *
     * Retrieve list of timeline items..
     *
     * @covers ::getTimeline
     */
    public function testGetTimeline()
    {
        self::markTestIncomplete(
            'Test of "getTimeline" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getTimelineItem
     *
     * Retrieve a single timeline item..
     *
     * @covers ::getTimelineItem
     */
    public function testGetTimelineItem()
    {
        self::markTestIncomplete(
            'Test of "getTimelineItem" method has not been implemented yet.'
        );
    }
}
