<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * CalendarEvent
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CalendarEvent extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "example" : "55"
    },
    "instance" : {
      "type" : "string",
      "example" : "0"
    },
    "source" : {
      "type" : "string",
      "example" : "3939"
    },
    "created_timestamp" : {
      "type" : "string",
      "example" : "1755506045"
    },
    "updated_timestamp" : {
      "type" : "string",
      "example" : "0"
    },
    "external_uid" : {
      "type" : "string",
      "nullable" : true,
      "example" : "27"
    },
    "title" : {
      "type" : "string",
      "nullable" : true,
      "example" : "My Title"
    },
    "description" : {
      "type" : "string",
      "nullable" : true
    },
    "start_timestamp" : {
      "type" : "string",
      "example" : "1754289000"
    },
    "end_timestamp" : {
      "type" : "string",
      "example" : "1754292600"
    },
    "organiser" : {
      "type" : "string",
      "nullable" : true
    },
    "attendee" : {
      "type" : "string",
      "nullable" : true
    },
    "status" : {
      "type" : "string",
      "nullable" : true
    },
    "location" : {
      "type" : "string",
      "nullable" : true
    },
    "type" : {
      "type" : "string",
      "nullable" : true
    },
    "tags" : {
      "type" : "string",
      "nullable" : true
    },
    "trigger" : {
      "type" : "string",
      "nullable" : true
    },
    "action" : {
      "type" : "string",
      "nullable" : true
    },
    "reminder_description" : {
      "type" : "string",
      "nullable" : true
    },
    "context_name" : {
      "type" : "string",
      "nullable" : true
    }
  },
  "description" : "A calendar event returned from the API"
}
SCHEMA;
}
