<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * CalendarEventCommonRequestBodyFields
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CalendarEventCommonRequestBodyFields extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "title" : {
      "type" : "string",
      "description" : "Title of the event",
      "example" : "Lunch with Ellen"
    },
    "description" : {
      "type" : "string",
      "description" : "Detailed description of the event",
      "example" : "Meeting to discuss expectations"
    },
    "start_timestamp" : {
      "type" : "integer",
      "description" : "Start date and time as Unix timestamp",
      "format" : "int64",
      "example" : 1754289000
    },
    "end_timestamp" : {
      "type" : "integer",
      "description" : "End date and time as Unix timestamp",
      "format" : "int64",
      "example" : 1754289000
    },
    "status" : {
      "type" : "string",
      "description" : "Status of the event",
      "example" : "INVITED",
      "default" : "TENTATIVE",
      "enum" : [ "INVITED", "TENTATIVE", "CONFIRMED", "REJECTED", "CANCELLED" ]
    },
    "organiser" : {
      "type" : "string",
      "description" : "Creator of the event",
      "example" : "Sally Adams"
    },
    "attendee" : {
      "type" : "string",
      "description" : "Person attending the event",
      "example" : "Ellen Munro"
    },
    "location" : {
      "type" : "string",
      "description" : "Event location",
      "example" : "Main building"
    }
  },
  "description" : "Common fields shared across all calendar event types"
}
SCHEMA;
}
