<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * ReferralListResponseReferralsInner
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ReferralListResponseReferralsInner extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "example" : 1
    },
    "created_timestamp" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1642137822
    },
    "service_id" : {
      "type" : "integer",
      "example" : 2
    },
    "service_name" : {
      "type" : "string",
      "example" : "My Service Name"
    },
    "service_description" : {
      "type" : "string",
      "example" : "My service description"
    },
    "service_contact_number" : {
      "type" : "string",
      "example" : "07987654321"
    },
    "service_email" : {
      "type" : "string",
      "example" : "my_service@email.com"
    },
    "service_url" : {
      "type" : "string",
      "example" : "my-service.com"
    },
    "type" : {
      "type" : "string",
      "example" : "Self Referred"
    },
    "status" : {
      "type" : "string",
      "example" : "Rejected",
      "enum" : [ "Referred", "In Progress", "Accepted", "Rejected" ]
    }
  }
}
SCHEMA;
}
