<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * ReferralCommonRequestBodyFields
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ReferralCommonRequestBodyFields extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "service_id" : {
      "type" : "integer",
      "description" : "ID of the service being referred to",
      "example" : 1
    },
    "referree_background" : {
      "type" : "string",
      "description" : "Background information about the referree",
      "example" : "Client has a history of..."
    },
    "referree_requirements" : {
      "type" : "string",
      "description" : "Requirements of the referree",
      "example" : "Needs support with..."
    },
    "referree_availability" : {
      "$ref" : "#/components/schemas/ReferralCommonRequestBodyFields_referree_availability"
    },
    "referrer_name" : {
      "type" : "string",
      "description" : "Name of the person making the referral",
      "example" : "John Doe"
    },
    "service_name" : {
      "type" : "string",
      "description" : "Name of the service",
      "example" : "Community Support"
    },
    "service_description" : {
      "type" : "string",
      "description" : "Description of the service",
      "example" : "Provides support for..."
    },
    "service_url" : {
      "type" : "string",
      "description" : "URL of the service",
      "format" : "uri",
      "example" : "https://example.com"
    },
    "service_email" : {
      "type" : "string",
      "description" : "Email address of the service",
      "format" : "email",
      "example" : "service@example.com"
    },
    "contact_number" : {
      "type" : "string",
      "description" : "Contact number for the service",
      "example" : "+441234567890"
    },
    "memo" : {
      "type" : "string",
      "description" : "Internal memo or notes",
      "example" : "Additional notes"
    },
    "start_time" : {
      "type" : "integer",
      "description" : "Start time as a Unix timestamp",
      "format" : "int64",
      "example" : 1754289000
    }
  },
  "description" : "Common fields shared across all referral types"
}
SCHEMA;
}
