<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * SecureMessage
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SecureMessage extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "description" : "Message ID",
      "example" : "361"
    },
    "conversation_id" : {
      "type" : "string",
      "description" : "Conversation identifier",
      "example" : "referral-102"
    },
    "message_to" : {
      "type" : "string",
      "description" : "Recipient of the message (present on sent messages)",
      "example" : "Another person"
    },
    "message_from" : {
      "type" : "string",
      "description" : "Sender of the message (present on received messages)",
      "example" : ""
    },
    "time_sent" : {
      "type" : "string",
      "description" : "Timestamp when message was sent",
      "example" : "1774459015"
    },
    "time_received" : {
      "type" : "string",
      "description" : "Timestamp when message was received",
      "example" : "1774459017"
    },
    "message_content" : {
      "type" : "string",
      "description" : "Content of the message",
      "example" : "Hello"
    },
    "status" : {
      "type" : "string",
      "description" : "Message status",
      "example" : "sent",
      "enum" : [ "sent", "received" ]
    }
  },
  "description" : "A single message within a conversation"
}
SCHEMA;
}
