<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * TimelineItemSecureMessage
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimelineItemSecureMessage extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "feature_block" : {
      "type" : "string",
      "description" : "Type of feature block this timeline item belongs to",
      "example" : "secure_messages"
    },
    "feature_block_id" : {
      "type" : "integer",
      "description" : "ID of the feature block",
      "example" : 364
    },
    "start_timestamp" : {
      "type" : "string",
      "description" : "Formatted start timestamp for display",
      "example" : "26th March 2026, 4:15 pm"
    },
    "item_timestamp" : {
      "type" : "integer",
      "description" : "Raw timestamp of the timeline item",
      "format" : "int64",
      "example" : 1774541713
    },
    "created_timestamp" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774541713
    },
    "updated_timestamp" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774541713
    },
    "conversation_id" : {
      "type" : "string",
      "description" : "Conversation identifier",
      "example" : "referral-104"
    },
    "time_sent" : {
      "type" : "string",
      "description" : "Timestamp when message was sent",
      "example" : ""
    },
    "time_received" : {
      "type" : "string",
      "description" : "Timestamp when message was received",
      "example" : "1774541713"
    },
    "message_from" : {
      "type" : "string",
      "description" : "Sender of the message (present on received messages)",
      "example" : "Another person"
    },
    "message_to" : {
      "type" : "string",
      "description" : "Recipient of the message (present on sent messages)",
      "example" : ""
    },
    "message_content" : {
      "type" : "string",
      "description" : "Content of the message",
      "example" : "Hello"
    }
  },
  "description" : "A single timeline item representing a secure message"
}
SCHEMA;
}
