<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * TimelineItemReferral
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimelineItemReferral extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "feature_block" : {
      "type" : "string",
      "description" : "Type of feature block this timeline item belongs to",
      "example" : "referrals"
    },
    "feature_block_id" : {
      "type" : "integer",
      "description" : "ID of the feature block record i.e. the referral id",
      "example" : 103
    },
    "instance" : {
      "type" : "string",
      "example" : "0"
    },
    "source" : {
      "type" : "string",
      "description" : "The context within which this record was created i.e. the specific connection",
      "example" : "3939-40102"
    },
    "created_timestamp" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774540331
    },
    "updated_timestamp" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774540331
    },
    "service_id" : {
      "type" : "integer",
      "description" : "The id of the service that the referral relates to",
      "example" : 2
    },
    "service_name" : {
      "type" : "string",
      "example" : "Grad Careers UK"
    },
    "service_description" : {
      "type" : "string",
      "example" : "Comprehensive career guidance and counselling"
    },
    "service_url" : {
      "type" : "string",
      "example" : "https://gradcareersuk.example.com"
    },
    "service_email" : {
      "type" : "string",
      "example" : "contact@gradcareersuk.example.com"
    },
    "contact_name" : {
      "type" : "string",
      "example" : "John Smith"
    },
    "contact_title" : {
      "type" : "string",
      "example" : "Senior Consultant"
    },
    "contact_number" : {
      "type" : "string",
      "example" : "07987654321"
    },
    "referrer_name" : {
      "type" : "string",
      "example" : "Marco Thompson"
    },
    "status" : {
      "type" : "string",
      "example" : "Referred",
      "enum" : [ "Referred", "In Progress", "Accepted", "Rejected" ]
    },
    "external_id" : {
      "type" : "string",
      "example" : "EXT12345"
    },
    "start_time" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774540331
    },
    "end_time" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1774543931
    },
    "is_processed" : {
      "type" : "boolean",
      "example" : false
    },
    "complete_time" : {
      "type" : "integer",
      "example" : 0
    },
    "memo" : {
      "type" : "string",
      "example" : "Referral memo for follow-up"
    },
    "duration" : {
      "type" : "string",
      "example" : "1 hour"
    },
    "referree_background" : {
      "type" : "string",
      "example" : "Has 5 years of experience in marketing"
    },
    "referree_requirements" : {
      "type" : "string",
      "example" : "Requires guidance on career path"
    },
    "referree_availability" : {
      "type" : "object",
      "description" : "Availability of the referree in AM/PM slots"
    },
    "type" : {
      "type" : "string",
      "example" : "Self Referred"
    },
    "start_timestamp" : {
      "type" : "string",
      "example" : "26th March 2026, 3:52 pm"
    }
  },
  "description" : "A single timeline item representing a referral"
}
SCHEMA;
}
