<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * TimelineItemCalendarEvent
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimelineItemCalendarEvent extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "feature_block" : {
      "type" : "string",
      "description" : "Type of feature block this timeline item belongs to",
      "example" : "calendar"
    },
    "feature_block_id" : {
      "type" : "integer",
      "description" : "ID of the feature block",
      "example" : 82
    },
    "instance" : {
      "type" : "string",
      "example" : "0"
    },
    "source" : {
      "type" : "string",
      "example" : "3939-40102"
    },
    "created_timestamp" : {
      "type" : "string",
      "example" : "1764071427"
    },
    "updated_timestamp" : {
      "type" : "string",
      "example" : "1764071427"
    },
    "external_uid" : {
      "type" : "string",
      "nullable" : true,
      "example" : ""
    },
    "title" : {
      "type" : "string",
      "nullable" : true,
      "example" : "My Event"
    },
    "description" : {
      "type" : "string",
      "nullable" : true,
      "example" : "My Description"
    },
    "start_timestamp" : {
      "type" : "string",
      "example" : "4th August 2025, 6:30 am"
    },
    "end_timestamp" : {
      "type" : "string",
      "example" : "4th August 2025, 7:30 am"
    },
    "organiser" : {
      "type" : "string",
      "nullable" : true
    },
    "attendee" : {
      "type" : "string",
      "nullable" : true
    },
    "status" : {
      "type" : "string",
      "nullable" : true,
      "example" : "TENTATIVE"
    },
    "location" : {
      "type" : "string",
      "nullable" : true
    },
    "type" : {
      "type" : "string",
      "nullable" : true
    },
    "tags" : {
      "type" : "string",
      "nullable" : true
    },
    "trigger" : {
      "type" : "string",
      "nullable" : true
    },
    "action" : {
      "type" : "string",
      "nullable" : true
    },
    "reminder_description" : {
      "type" : "string",
      "nullable" : true
    },
    "duration_string" : {
      "type" : "string",
      "example" : "1 hour "
    },
    "duration_of_event" : {
      "type" : "number",
      "format" : "float",
      "example" : 0.041666666666666664
    }
  },
  "description" : "A single timeline item representing a calendar event"
}
SCHEMA;
}
