<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * TimelineResponseTimelineInnerOneOf2
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimelineResponseTimelineInnerOneOf2 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "example" : 303
    },
    "feature_block" : {
      "type" : "string",
      "example" : "calendar"
    },
    "feature_block_id" : {
      "type" : "string",
      "example" : "80"
    },
    "start_timestamp" : {
      "type" : "string",
      "example" : "2025-08-04T06:30:00Z"
    },
    "item_timestamp" : {
      "type" : "integer",
      "example" : 1754289000
    },
    "end_timestamp" : {
      "type" : "string",
      "example" : "2025-08-04T07:30:00Z"
    },
    "title" : {
      "type" : "string",
      "example" : "Quarterly Business Review"
    },
    "location" : {
      "type" : "string",
      "example" : "Zoom Meeting Room 1"
    },
    "organiser" : {
      "type" : "string",
      "example" : "Alice Johnson"
    },
    "description" : {
      "type" : "string",
      "example" : "Review of Q2 performance metrics and planning for Q3"
    },
    "status" : {
      "type" : "string",
      "example" : "CONFIRMED"
    },
    "duration_string" : {
      "type" : "string",
      "example" : "1 hour"
    },
    "duration_of_event" : {
      "type" : "number",
      "example" : 1
    }
  },
  "description" : "Calendar event item"
}
SCHEMA;
}
