<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use Mydex\ApiPdxSdk\Slim4\BaseModel;

/**
 * TimelineResponseTimelineInnerOneOf1
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimelineResponseTimelineInnerOneOf1 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\Mydex\ApiPdxSdk\Slim4\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "example" : 202
    },
    "feature_block" : {
      "type" : "string",
      "example" : "secure_messages"
    },
    "feature_block_id" : {
      "type" : "string",
      "example" : "1"
    },
    "start_timestamp" : {
      "type" : "string",
      "example" : "2025-03-26T10:00:00Z"
    },
    "item_timestamp" : {
      "type" : "integer",
      "example" : 1774459050
    },
    "created_timestamp" : {
      "type" : "integer",
      "example" : 1774459050
    },
    "message_from" : {
      "type" : "string",
      "example" : "EmilyQ45879"
    },
    "message_to" : {
      "type" : "string",
      "example" : ""
    },
    "message_content" : {
      "type" : "string",
      "example" : "Please review the attached referral details before the meeting."
    }
  },
  "description" : "Secure message item"
}
SCHEMA;
}
