<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace Mydex\ApiPdxSdk\Slim4\App;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;
use Dyorg\TokenAuthentication;
use Mydex\ApiPdxSdk\Slim4\Auth\OAuthAuthenticator;

/**
 * RegisterRoutes Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class RegisterRoutes
{
    /** @var array[] list of all api operations */
    private $operations = [
        [
            'httpMethod' => 'DELETE',
            'basePathWithoutHost' => '',
            'path' => '/calendar/delete-event',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'deleteCalendarEvent',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/DeleteResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'delete:/calendar/delete-event', // Delete a calendar event
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/calendar/get-appointments',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'getCalendarAppointments',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/GetAppointmentsResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/calendar/get-appointments', // Read calendar appointments
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/calendar/get-events',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'getCalendarEvents',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/GetEventsResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/calendar/get-events', // Read calendar events
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/calendar/add-appointment',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'postCalendarAppointment',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'post:/calendar/add-appointment', // Create a calendar appointment
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/calendar/add-event',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'postCalendarEvent',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'post:/calendar/add-event', // Create a calendar event
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'PUT',
            'basePathWithoutHost' => '',
            'path' => '/calendar/update-event',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractCalendarApi',
            'userClassname' => 'CalendarApi',
            'operationId' => 'putCalendarEvent',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/UpdateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'put:/calendar/update-event', // Update a calendar event
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/referrals/read-all',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractReferralsApi',
            'userClassname' => 'ReferralsApi',
            'operationId' => 'getAllReferrals',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ReferralListResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/referrals/read-all', // Read all referrals
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/referrals/read-single',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractReferralsApi',
            'userClassname' => 'ReferralsApi',
            'operationId' => 'getSingleReferral',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ReferralSingleResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/referrals/read-single', // Read a single referral
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/referrals/self-refer',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractReferralsApi',
            'userClassname' => 'ReferralsApi',
            'operationId' => 'postSelfReferral',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'post:/referrals/self-refer', // Make a self-referral to a service
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'PUT',
            'basePathWithoutHost' => '',
            'path' => '/referrals/update-status',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractReferralsApi',
            'userClassname' => 'ReferralsApi',
            'operationId' => 'updateReferralStatus',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/UpdateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'put:/referrals/update-status', // Update the status of a referral
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/secure-messages/conversation',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractSecureMessagesApi',
            'userClassname' => 'SecureMessagesApi',
            'operationId' => 'getSecureMessageConversation',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/SecureMessageConversationResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/secure-messages/conversation', // Read messages grouped by the specified conversation
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/secure-messages/receive',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractSecureMessagesApi',
            'userClassname' => 'SecureMessagesApi',
            'operationId' => 'postSecureMessageReceive',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'post:/secure-messages/receive', // Send a message TO the member&#39;s PDS
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '',
            'path' => '/secure-messages/send',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractSecureMessagesApi',
            'userClassname' => 'SecureMessagesApi',
            'operationId' => 'postSecureMessageSend',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successfully created record.",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/CreateResponse"
      }
    }
  }
}',
                ],
                '400' => [
                    'jsonSchema' => '{
  "description" : "Bad Request",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/ErrorResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'post:/secure-messages/send', // Send a message FROM the member&#39;s PDS
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/timeline',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractTimelineApi',
            'userClassname' => 'TimelineApi',
            'operationId' => 'getTimeline',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/TimelineResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/timeline', // Read a list of timeline items
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '',
            'path' => '/timeline/single-item',
            'apiPackage' => 'Mydex\ApiPdxSdk\Slim4\Api',
            'classname' => 'AbstractTimelineApi',
            'userClassname' => 'TimelineApi',
            'operationId' => 'getTimelineItem',
            'responses' => [
                '200' => [
                    'jsonSchema' => '{
  "description" : "Successful response",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/TimelineSingleItemResponse"
      }
    }
  }
}',
                ],
                '401' => [
                    'jsonSchema' => '{
  "description" : "Unauthorized",
  "content" : {
    "application/json" : {
      "schema" : {
        "$ref" : "#/components/schemas/AuthErrorResponse"
      }
    }
  }
}',
                ],
            ],
            'authMethods' => [
                // oauth2 security schema named 'oauth2'
                [
                    'type' => 'oauth2',
                    'isBasic' => false,
                    'isBearer' => false,
                    'isApiKey' => false,
                    'isOAuth' => true,
                    'scopes' => [
                        'get:/timeline/single-item', // Read a single item from the timeline
                        'mydex:pdx', // Global access scope
                    ],
                ],
            ],
        ],
    ];

    /**
     * Add routes to Slim app.
     *
     * @param \Slim\App $app Pre-configured Slim application instance
     *
     * @throws HttpNotImplementedException When implementation class doesn't exists
     */
    public function __invoke(\Slim\App $app): void
    {
        $app->options('/{routes:.*}', function (ServerRequestInterface $request, ResponseInterface $response) {
            // CORS Pre-Flight OPTIONS Request Handler
            return $response;
        });

        // create mock middleware factory
        /** @var \Psr\Container\ContainerInterface */
        $container = $app->getContainer();
        /** @var \OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory|null */
        $mockMiddlewareFactory = null;
        if ($container->has(\OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory::class)) {
            // I know, anti-pattern. Don't retrieve dependency directly from container
            $mockMiddlewareFactory = $container->get(\OpenAPIServer\Mock\OpenApiDataMockerRouteMiddlewareFactory::class);
        }

        foreach ($this->operations as $operation) {
            $callback = function (ServerRequestInterface $request) use ($operation) {
                $message = "How about extending {$operation['classname']} by {$operation['apiPackage']}\\{$operation['userClassname']} class implementing {$operation['operationId']} as a {$operation['httpMethod']} method?";
                throw new HttpNotImplementedException($request, $message);
            };
            $middlewares = [];

            if (class_exists("\\{$operation['apiPackage']}\\{$operation['userClassname']}")) {
                // Notice how we register the controller using the class name?
                // PHP-DI will instantiate the class for us only when it's actually necessary
                $callback = ["\\{$operation['apiPackage']}\\{$operation['userClassname']}", $operation['operationId']];
            }

            if ($mockMiddlewareFactory) {
                $mockSchemaResponses = array_map(function ($item) {
                    return json_decode($item['jsonSchema'], true);
                }, $operation['responses']);
                $middlewares[] = $mockMiddlewareFactory->create($mockSchemaResponses);
            }

            $route = $app->map(
                [$operation['httpMethod']],
                "{$operation['basePathWithoutHost']}{$operation['path']}",
                $callback
            )->setName($operation['operationId']);

            // Add authentication middleware based on the operation's authMethods
            if ($operation['authMethods']) {
                foreach ($operation['authMethods'] as $authMethod) {
                    if ($authMethod['isOAuth']) {
                        $route->add(new TokenAuthentication([
                            'path' => '/',
                            'authenticator' => new OAuthAuthenticator($authMethod['scopes']),
                            'regex' => '/Bearer\s+(.*)$/i',
                            'header' => 'Authorization',
                            'parameter' => null,
                            'cookie' => null,
                            'argument' => null,
                            'attribute' => 'authorization_token',
                            'error' => ['Mydex\ApiPdxSdk\Slim4\Auth\OAuthAuthenticator', 'handleUnauthorized'],
                        ]));
                    }
                }
            }

            foreach ($middlewares as $middleware) {
                $route->add($middleware);
            }
        }
    }
}
