<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\CalendarAppointmentCreateRequestBody;

/**
 * CalendarAppointmentCreateRequestBodyTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\CalendarAppointmentCreateRequestBody
 */
class CalendarAppointmentCreateRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CalendarAppointmentCreateRequestBody"
     */
    public function testCalendarAppointmentCreateRequestBody()
    {
        $testCalendarAppointmentCreateRequestBody = new CalendarAppointmentCreateRequestBody();
        $namespacedClassname = CalendarAppointmentCreateRequestBody::getModelsNamespace() . '\\CalendarAppointmentCreateRequestBody';
        $this->assertSame('\\' . CalendarAppointmentCreateRequestBody::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        self::markTestIncomplete(
            'Test of "title" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        self::markTestIncomplete(
            'Test of "description" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTimestamp"
     */
    public function testPropertyEndTimestamp()
    {
        self::markTestIncomplete(
            'Test of "endTimestamp" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "organiser"
     */
    public function testPropertyOrganiser()
    {
        self::markTestIncomplete(
            'Test of "organiser" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "attendee"
     */
    public function testPropertyAttendee()
    {
        self::markTestIncomplete(
            'Test of "attendee" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        self::markTestIncomplete(
            'Test of "location" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
        self::markTestIncomplete(
            'Test of "context" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contextId"
     */
    public function testPropertyContextId()
    {
        self::markTestIncomplete(
            'Test of "contextId" property in "CalendarAppointmentCreateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = CalendarAppointmentCreateRequestBody::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

