<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\ReferralStatusUpdateRequestBody;

/**
 * ReferralStatusUpdateRequestBodyTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\ReferralStatusUpdateRequestBody
 */
class ReferralStatusUpdateRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReferralStatusUpdateRequestBody"
     */
    public function testReferralStatusUpdateRequestBody()
    {
        $testReferralStatusUpdateRequestBody = new ReferralStatusUpdateRequestBody();
        $namespacedClassname = ReferralStatusUpdateRequestBody::getModelsNamespace() . '\\ReferralStatusUpdateRequestBody';
        $this->assertSame('\\' . ReferralStatusUpdateRequestBody::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "ReferralStatusUpdateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        self::markTestIncomplete(
            'Test of "id" property in "ReferralStatusUpdateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "ReferralStatusUpdateRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ReferralStatusUpdateRequestBody::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

