<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\ReferralCommonRequestBodyFieldsReferreeAvailability;

/**
 * ReferralCommonRequestBodyFieldsReferreeAvailabilityTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\ReferralCommonRequestBodyFieldsReferreeAvailability
 */
class ReferralCommonRequestBodyFieldsReferreeAvailabilityTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReferralCommonRequestBodyFieldsReferreeAvailability"
     */
    public function testReferralCommonRequestBodyFieldsReferreeAvailability()
    {
        $testReferralCommonRequestBodyFieldsReferreeAvailability = new ReferralCommonRequestBodyFieldsReferreeAvailability();
        $namespacedClassname = ReferralCommonRequestBodyFieldsReferreeAvailability::getModelsNamespace() . '\\ReferralCommonRequestBodyFieldsReferreeAvailability';
        $this->assertSame('\\' . ReferralCommonRequestBodyFieldsReferreeAvailability::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "ReferralCommonRequestBodyFieldsReferreeAvailability" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "aM"
     */
    public function testPropertyAM()
    {
        self::markTestIncomplete(
            'Test of "aM" property in "ReferralCommonRequestBodyFieldsReferreeAvailability" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "pM"
     */
    public function testPropertyPM()
    {
        self::markTestIncomplete(
            'Test of "pM" property in "ReferralCommonRequestBodyFieldsReferreeAvailability" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ReferralCommonRequestBodyFieldsReferreeAvailability::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

