<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\ReferralListResponseReferralsInner;

/**
 * ReferralListResponseReferralsInnerTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\ReferralListResponseReferralsInner
 */
class ReferralListResponseReferralsInnerTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReferralListResponseReferralsInner"
     */
    public function testReferralListResponseReferralsInner()
    {
        $testReferralListResponseReferralsInner = new ReferralListResponseReferralsInner();
        $namespacedClassname = ReferralListResponseReferralsInner::getModelsNamespace() . '\\ReferralListResponseReferralsInner';
        $this->assertSame('\\' . ReferralListResponseReferralsInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        self::markTestIncomplete(
            'Test of "id" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdTimestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "createdTimestamp" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceId"
     */
    public function testPropertyServiceId()
    {
        self::markTestIncomplete(
            'Test of "serviceId" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceName"
     */
    public function testPropertyServiceName()
    {
        self::markTestIncomplete(
            'Test of "serviceName" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceDescription"
     */
    public function testPropertyServiceDescription()
    {
        self::markTestIncomplete(
            'Test of "serviceDescription" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceContactNumber"
     */
    public function testPropertyServiceContactNumber()
    {
        self::markTestIncomplete(
            'Test of "serviceContactNumber" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceEmail"
     */
    public function testPropertyServiceEmail()
    {
        self::markTestIncomplete(
            'Test of "serviceEmail" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceUrl"
     */
    public function testPropertyServiceUrl()
    {
        self::markTestIncomplete(
            'Test of "serviceUrl" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        self::markTestIncomplete(
            'Test of "type" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "ReferralListResponseReferralsInner" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ReferralListResponseReferralsInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

