<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\SecureMessageSendRequest;

/**
 * SecureMessageSendRequestTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\SecureMessageSendRequest
 */
class SecureMessageSendRequestTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SecureMessageSendRequest"
     */
    public function testSecureMessageSendRequest()
    {
        $testSecureMessageSendRequest = new SecureMessageSendRequest();
        $namespacedClassname = SecureMessageSendRequest::getModelsNamespace() . '\\SecureMessageSendRequest';
        $this->assertSame('\\' . SecureMessageSendRequest::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "SecureMessageSendRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageContent"
     */
    public function testPropertyMessageContent()
    {
        self::markTestIncomplete(
            'Test of "messageContent" property in "SecureMessageSendRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "conversationId"
     */
    public function testPropertyConversationId()
    {
        self::markTestIncomplete(
            'Test of "conversationId" property in "SecureMessageSendRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageTo"
     */
    public function testPropertyMessageTo()
    {
        self::markTestIncomplete(
            'Test of "messageTo" property in "SecureMessageSendRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = SecureMessageSendRequest::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

