<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\SelfReferralRequestBody;

/**
 * SelfReferralRequestBodyTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\SelfReferralRequestBody
 */
class SelfReferralRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SelfReferralRequestBody"
     */
    public function testSelfReferralRequestBody()
    {
        $testSelfReferralRequestBody = new SelfReferralRequestBody();
        $namespacedClassname = SelfReferralRequestBody::getModelsNamespace() . '\\SelfReferralRequestBody';
        $this->assertSame('\\' . SelfReferralRequestBody::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceId"
     */
    public function testPropertyServiceId()
    {
        self::markTestIncomplete(
            'Test of "serviceId" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeBackground"
     */
    public function testPropertyReferreeBackground()
    {
        self::markTestIncomplete(
            'Test of "referreeBackground" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeRequirements"
     */
    public function testPropertyReferreeRequirements()
    {
        self::markTestIncomplete(
            'Test of "referreeRequirements" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeAvailability"
     */
    public function testPropertyReferreeAvailability()
    {
        self::markTestIncomplete(
            'Test of "referreeAvailability" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referrerName"
     */
    public function testPropertyReferrerName()
    {
        self::markTestIncomplete(
            'Test of "referrerName" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceName"
     */
    public function testPropertyServiceName()
    {
        self::markTestIncomplete(
            'Test of "serviceName" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceDescription"
     */
    public function testPropertyServiceDescription()
    {
        self::markTestIncomplete(
            'Test of "serviceDescription" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceUrl"
     */
    public function testPropertyServiceUrl()
    {
        self::markTestIncomplete(
            'Test of "serviceUrl" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceEmail"
     */
    public function testPropertyServiceEmail()
    {
        self::markTestIncomplete(
            'Test of "serviceEmail" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactNumber"
     */
    public function testPropertyContactNumber()
    {
        self::markTestIncomplete(
            'Test of "contactNumber" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
        self::markTestIncomplete(
            'Test of "memo" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTime"
     */
    public function testPropertyStartTime()
    {
        self::markTestIncomplete(
            'Test of "startTime" property in "SelfReferralRequestBody" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = SelfReferralRequestBody::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

