<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\TimelineSingleItemResponseTimelineItem;

/**
 * TimelineSingleItemResponseTimelineItemTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\TimelineSingleItemResponseTimelineItem
 */
class TimelineSingleItemResponseTimelineItemTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimelineSingleItemResponseTimelineItem"
     */
    public function testTimelineSingleItemResponseTimelineItem()
    {
        $testTimelineSingleItemResponseTimelineItem = new TimelineSingleItemResponseTimelineItem();
        $namespacedClassname = TimelineSingleItemResponseTimelineItem::getModelsNamespace() . '\\TimelineSingleItemResponseTimelineItem';
        $this->assertSame('\\' . TimelineSingleItemResponseTimelineItem::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlock"
     */
    public function testPropertyFeatureBlock()
    {
        self::markTestIncomplete(
            'Test of "featureBlock" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlockId"
     */
    public function testPropertyFeatureBlockId()
    {
        self::markTestIncomplete(
            'Test of "featureBlockId" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "instance"
     */
    public function testPropertyInstance()
    {
        self::markTestIncomplete(
            'Test of "instance" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        self::markTestIncomplete(
            'Test of "source" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdTimestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "createdTimestamp" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "updatedTimestamp"
     */
    public function testPropertyUpdatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "updatedTimestamp" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceId"
     */
    public function testPropertyServiceId()
    {
        self::markTestIncomplete(
            'Test of "serviceId" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceName"
     */
    public function testPropertyServiceName()
    {
        self::markTestIncomplete(
            'Test of "serviceName" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceDescription"
     */
    public function testPropertyServiceDescription()
    {
        self::markTestIncomplete(
            'Test of "serviceDescription" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceUrl"
     */
    public function testPropertyServiceUrl()
    {
        self::markTestIncomplete(
            'Test of "serviceUrl" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceEmail"
     */
    public function testPropertyServiceEmail()
    {
        self::markTestIncomplete(
            'Test of "serviceEmail" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactName"
     */
    public function testPropertyContactName()
    {
        self::markTestIncomplete(
            'Test of "contactName" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactTitle"
     */
    public function testPropertyContactTitle()
    {
        self::markTestIncomplete(
            'Test of "contactTitle" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactNumber"
     */
    public function testPropertyContactNumber()
    {
        self::markTestIncomplete(
            'Test of "contactNumber" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referrerName"
     */
    public function testPropertyReferrerName()
    {
        self::markTestIncomplete(
            'Test of "referrerName" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
        self::markTestIncomplete(
            'Test of "externalId" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTime"
     */
    public function testPropertyStartTime()
    {
        self::markTestIncomplete(
            'Test of "startTime" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTime"
     */
    public function testPropertyEndTime()
    {
        self::markTestIncomplete(
            'Test of "endTime" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isProcessed"
     */
    public function testPropertyIsProcessed()
    {
        self::markTestIncomplete(
            'Test of "isProcessed" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "completeTime"
     */
    public function testPropertyCompleteTime()
    {
        self::markTestIncomplete(
            'Test of "completeTime" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
        self::markTestIncomplete(
            'Test of "memo" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        self::markTestIncomplete(
            'Test of "duration" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeBackground"
     */
    public function testPropertyReferreeBackground()
    {
        self::markTestIncomplete(
            'Test of "referreeBackground" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeRequirements"
     */
    public function testPropertyReferreeRequirements()
    {
        self::markTestIncomplete(
            'Test of "referreeRequirements" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeAvailability"
     */
    public function testPropertyReferreeAvailability()
    {
        self::markTestIncomplete(
            'Test of "referreeAvailability" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        self::markTestIncomplete(
            'Test of "type" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "itemTimestamp"
     */
    public function testPropertyItemTimestamp()
    {
        self::markTestIncomplete(
            'Test of "itemTimestamp" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "conversationId"
     */
    public function testPropertyConversationId()
    {
        self::markTestIncomplete(
            'Test of "conversationId" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "timeSent"
     */
    public function testPropertyTimeSent()
    {
        self::markTestIncomplete(
            'Test of "timeSent" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "timeReceived"
     */
    public function testPropertyTimeReceived()
    {
        self::markTestIncomplete(
            'Test of "timeReceived" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageFrom"
     */
    public function testPropertyMessageFrom()
    {
        self::markTestIncomplete(
            'Test of "messageFrom" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageTo"
     */
    public function testPropertyMessageTo()
    {
        self::markTestIncomplete(
            'Test of "messageTo" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageContent"
     */
    public function testPropertyMessageContent()
    {
        self::markTestIncomplete(
            'Test of "messageContent" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "externalUid"
     */
    public function testPropertyExternalUid()
    {
        self::markTestIncomplete(
            'Test of "externalUid" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        self::markTestIncomplete(
            'Test of "title" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        self::markTestIncomplete(
            'Test of "description" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTimestamp"
     */
    public function testPropertyEndTimestamp()
    {
        self::markTestIncomplete(
            'Test of "endTimestamp" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "organiser"
     */
    public function testPropertyOrganiser()
    {
        self::markTestIncomplete(
            'Test of "organiser" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "attendee"
     */
    public function testPropertyAttendee()
    {
        self::markTestIncomplete(
            'Test of "attendee" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        self::markTestIncomplete(
            'Test of "location" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
        self::markTestIncomplete(
            'Test of "tags" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trigger"
     */
    public function testPropertyTrigger()
    {
        self::markTestIncomplete(
            'Test of "trigger" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
        self::markTestIncomplete(
            'Test of "action" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "reminderDescription"
     */
    public function testPropertyReminderDescription()
    {
        self::markTestIncomplete(
            'Test of "reminderDescription" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationString"
     */
    public function testPropertyDurationString()
    {
        self::markTestIncomplete(
            'Test of "durationString" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationOfEvent"
     */
    public function testPropertyDurationOfEvent()
    {
        self::markTestIncomplete(
            'Test of "durationOfEvent" property in "TimelineSingleItemResponseTimelineItem" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimelineSingleItemResponseTimelineItem::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

