<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\TimelineResponseTimelineInnerOneOf1;

/**
 * TimelineResponseTimelineInnerOneOf1Test Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\TimelineResponseTimelineInnerOneOf1
 */
class TimelineResponseTimelineInnerOneOf1Test extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimelineResponseTimelineInnerOneOf1"
     */
    public function testTimelineResponseTimelineInnerOneOf1()
    {
        $testTimelineResponseTimelineInnerOneOf1 = new TimelineResponseTimelineInnerOneOf1();
        $namespacedClassname = TimelineResponseTimelineInnerOneOf1::getModelsNamespace() . '\\TimelineResponseTimelineInnerOneOf1';
        $this->assertSame('\\' . TimelineResponseTimelineInnerOneOf1::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        self::markTestIncomplete(
            'Test of "id" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlock"
     */
    public function testPropertyFeatureBlock()
    {
        self::markTestIncomplete(
            'Test of "featureBlock" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlockId"
     */
    public function testPropertyFeatureBlockId()
    {
        self::markTestIncomplete(
            'Test of "featureBlockId" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "itemTimestamp"
     */
    public function testPropertyItemTimestamp()
    {
        self::markTestIncomplete(
            'Test of "itemTimestamp" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdTimestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "createdTimestamp" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageFrom"
     */
    public function testPropertyMessageFrom()
    {
        self::markTestIncomplete(
            'Test of "messageFrom" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageTo"
     */
    public function testPropertyMessageTo()
    {
        self::markTestIncomplete(
            'Test of "messageTo" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "messageContent"
     */
    public function testPropertyMessageContent()
    {
        self::markTestIncomplete(
            'Test of "messageContent" property in "TimelineResponseTimelineInnerOneOf1" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimelineResponseTimelineInnerOneOf1::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

