<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\TimelineItemCalendarEvent;

/**
 * TimelineItemCalendarEventTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\TimelineItemCalendarEvent
 */
class TimelineItemCalendarEventTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimelineItemCalendarEvent"
     */
    public function testTimelineItemCalendarEvent()
    {
        $testTimelineItemCalendarEvent = new TimelineItemCalendarEvent();
        $namespacedClassname = TimelineItemCalendarEvent::getModelsNamespace() . '\\TimelineItemCalendarEvent';
        $this->assertSame('\\' . TimelineItemCalendarEvent::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlock"
     */
    public function testPropertyFeatureBlock()
    {
        self::markTestIncomplete(
            'Test of "featureBlock" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlockId"
     */
    public function testPropertyFeatureBlockId()
    {
        self::markTestIncomplete(
            'Test of "featureBlockId" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "instance"
     */
    public function testPropertyInstance()
    {
        self::markTestIncomplete(
            'Test of "instance" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        self::markTestIncomplete(
            'Test of "source" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdTimestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "createdTimestamp" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "updatedTimestamp"
     */
    public function testPropertyUpdatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "updatedTimestamp" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "externalUid"
     */
    public function testPropertyExternalUid()
    {
        self::markTestIncomplete(
            'Test of "externalUid" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        self::markTestIncomplete(
            'Test of "title" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        self::markTestIncomplete(
            'Test of "description" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTimestamp"
     */
    public function testPropertyEndTimestamp()
    {
        self::markTestIncomplete(
            'Test of "endTimestamp" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "organiser"
     */
    public function testPropertyOrganiser()
    {
        self::markTestIncomplete(
            'Test of "organiser" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "attendee"
     */
    public function testPropertyAttendee()
    {
        self::markTestIncomplete(
            'Test of "attendee" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        self::markTestIncomplete(
            'Test of "location" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        self::markTestIncomplete(
            'Test of "type" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
        self::markTestIncomplete(
            'Test of "tags" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trigger"
     */
    public function testPropertyTrigger()
    {
        self::markTestIncomplete(
            'Test of "trigger" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
        self::markTestIncomplete(
            'Test of "action" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "reminderDescription"
     */
    public function testPropertyReminderDescription()
    {
        self::markTestIncomplete(
            'Test of "reminderDescription" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationString"
     */
    public function testPropertyDurationString()
    {
        self::markTestIncomplete(
            'Test of "durationString" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationOfEvent"
     */
    public function testPropertyDurationOfEvent()
    {
        self::markTestIncomplete(
            'Test of "durationOfEvent" property in "TimelineItemCalendarEvent" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimelineItemCalendarEvent::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

