<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\TimelineItemReferral;

/**
 * TimelineItemReferralTest Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\TimelineItemReferral
 */
class TimelineItemReferralTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimelineItemReferral"
     */
    public function testTimelineItemReferral()
    {
        $testTimelineItemReferral = new TimelineItemReferral();
        $namespacedClassname = TimelineItemReferral::getModelsNamespace() . '\\TimelineItemReferral';
        $this->assertSame('\\' . TimelineItemReferral::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlock"
     */
    public function testPropertyFeatureBlock()
    {
        self::markTestIncomplete(
            'Test of "featureBlock" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlockId"
     */
    public function testPropertyFeatureBlockId()
    {
        self::markTestIncomplete(
            'Test of "featureBlockId" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "instance"
     */
    public function testPropertyInstance()
    {
        self::markTestIncomplete(
            'Test of "instance" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        self::markTestIncomplete(
            'Test of "source" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdTimestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "createdTimestamp" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "updatedTimestamp"
     */
    public function testPropertyUpdatedTimestamp()
    {
        self::markTestIncomplete(
            'Test of "updatedTimestamp" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceId"
     */
    public function testPropertyServiceId()
    {
        self::markTestIncomplete(
            'Test of "serviceId" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceName"
     */
    public function testPropertyServiceName()
    {
        self::markTestIncomplete(
            'Test of "serviceName" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceDescription"
     */
    public function testPropertyServiceDescription()
    {
        self::markTestIncomplete(
            'Test of "serviceDescription" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceUrl"
     */
    public function testPropertyServiceUrl()
    {
        self::markTestIncomplete(
            'Test of "serviceUrl" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "serviceEmail"
     */
    public function testPropertyServiceEmail()
    {
        self::markTestIncomplete(
            'Test of "serviceEmail" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactName"
     */
    public function testPropertyContactName()
    {
        self::markTestIncomplete(
            'Test of "contactName" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactTitle"
     */
    public function testPropertyContactTitle()
    {
        self::markTestIncomplete(
            'Test of "contactTitle" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "contactNumber"
     */
    public function testPropertyContactNumber()
    {
        self::markTestIncomplete(
            'Test of "contactNumber" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referrerName"
     */
    public function testPropertyReferrerName()
    {
        self::markTestIncomplete(
            'Test of "referrerName" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
        self::markTestIncomplete(
            'Test of "externalId" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTime"
     */
    public function testPropertyStartTime()
    {
        self::markTestIncomplete(
            'Test of "startTime" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTime"
     */
    public function testPropertyEndTime()
    {
        self::markTestIncomplete(
            'Test of "endTime" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isProcessed"
     */
    public function testPropertyIsProcessed()
    {
        self::markTestIncomplete(
            'Test of "isProcessed" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "completeTime"
     */
    public function testPropertyCompleteTime()
    {
        self::markTestIncomplete(
            'Test of "completeTime" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
        self::markTestIncomplete(
            'Test of "memo" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        self::markTestIncomplete(
            'Test of "duration" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeBackground"
     */
    public function testPropertyReferreeBackground()
    {
        self::markTestIncomplete(
            'Test of "referreeBackground" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeRequirements"
     */
    public function testPropertyReferreeRequirements()
    {
        self::markTestIncomplete(
            'Test of "referreeRequirements" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "referreeAvailability"
     */
    public function testPropertyReferreeAvailability()
    {
        self::markTestIncomplete(
            'Test of "referreeAvailability" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        self::markTestIncomplete(
            'Test of "type" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "TimelineItemReferral" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimelineItemReferral::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

