<?php

/**
 * PDX API
 * PHP version 8.1
 *
 * @package Mydex\ApiPdxSdk\Slim4
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace Mydex\ApiPdxSdk\Slim4\Model;

use PHPUnit\Framework\TestCase;
use Mydex\ApiPdxSdk\Slim4\Model\TimelineResponseTimelineInnerOneOf2;

/**
 * TimelineResponseTimelineInnerOneOf2Test Class Doc Comment
 *
 * @package Mydex\ApiPdxSdk\Slim4\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \Mydex\ApiPdxSdk\Slim4\Model\TimelineResponseTimelineInnerOneOf2
 */
class TimelineResponseTimelineInnerOneOf2Test extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimelineResponseTimelineInnerOneOf2"
     */
    public function testTimelineResponseTimelineInnerOneOf2()
    {
        $testTimelineResponseTimelineInnerOneOf2 = new TimelineResponseTimelineInnerOneOf2();
        $namespacedClassname = TimelineResponseTimelineInnerOneOf2::getModelsNamespace() . '\\TimelineResponseTimelineInnerOneOf2';
        $this->assertSame('\\' . TimelineResponseTimelineInnerOneOf2::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        self::markTestIncomplete(
            'Test of "id" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlock"
     */
    public function testPropertyFeatureBlock()
    {
        self::markTestIncomplete(
            'Test of "featureBlock" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "featureBlockId"
     */
    public function testPropertyFeatureBlockId()
    {
        self::markTestIncomplete(
            'Test of "featureBlockId" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "startTimestamp"
     */
    public function testPropertyStartTimestamp()
    {
        self::markTestIncomplete(
            'Test of "startTimestamp" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "itemTimestamp"
     */
    public function testPropertyItemTimestamp()
    {
        self::markTestIncomplete(
            'Test of "itemTimestamp" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "endTimestamp"
     */
    public function testPropertyEndTimestamp()
    {
        self::markTestIncomplete(
            'Test of "endTimestamp" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        self::markTestIncomplete(
            'Test of "title" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
        self::markTestIncomplete(
            'Test of "location" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "organiser"
     */
    public function testPropertyOrganiser()
    {
        self::markTestIncomplete(
            'Test of "organiser" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        self::markTestIncomplete(
            'Test of "description" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        self::markTestIncomplete(
            'Test of "status" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationString"
     */
    public function testPropertyDurationString()
    {
        self::markTestIncomplete(
            'Test of "durationString" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "durationOfEvent"
     */
    public function testPropertyDurationOfEvent()
    {
        self::markTestIncomplete(
            'Test of "durationOfEvent" property in "TimelineResponseTimelineInnerOneOf2" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimelineResponseTimelineInnerOneOf2::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

